### ISSUE TITLE
Cannot apply unknown utility class: flex-center

### ISSUE THREAD

**Issue by Devp-sriram** [adrianhajdin/iphone#22]
<h1>The utility classes on boiler plate code giving this error </h1>

<p> if i create the utility class by myself it working but if i copy paste snippet which you provide it's not working 
<br>
i am using tailwind "^4.0.14" in this version i don't have tailwind.config.js 
</P>

```bash
devp-sriram@compile-box:~/gsap/3d$ npm run dev

> 3d@0.0.0 dev
> vite
  VITE v6.2.2  ready in 988 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
10:20:39 PM [vite] Internal server error: Cannot apply unknown utility class: flex-center
  Plugin: @tailwindcss/vite:generate:serve
  File: /home/devp-sriram/gsap/3d/src/index.css
      at onInvalidCandidate (file:///home/devp-sriram/gsap/3d/node_modules/tailwindcss/dist/lib.mjs:6:346)
      at X (file:///home/devp-sriram/gsap/3d/node_modules/tailwindcss/dist/lib.mjs:1:109178)
      at ge (file:///home/devp-sriram/gsap/3d/node_modules/tailwindcss/dist/lib.mjs:6:310)
      at Zt (file:///home/devp-sriram/gsap/3d/node_modules/tailwindcss/dist/lib.mjs:22:780)
      at async Gr (file:///home/devp-sriram/gsap/3d/node_modules/tailwindcss/dist/lib.mjs:22:1071)
      at async Do (file:///home/devp-sriram/gsap/3d/node_modules/tailwindcss/dist/lib.mjs:22:1711)
      at async st (file:///home/devp-sriram/gsap/3d/node_modules/@tailwindcss/node/dist/index.mjs:10:3322)
      at async C.generate (file:///home/devp-sriram/gsap/3d/node_modules/@tailwindcss/vite/dist/index.mjs:1:3932)
      at async TransformPluginContext.transform (file:///home/devp-sriram/gsap/3d/node_modules/@tailwindcss/vite/dist/index.mjs:1:1959)
      at async EnvironmentPluginContainer.transform (file:///home/devp-sriram/gsap/3d/node_modules/vite/dist/node/chunks/dep-B0fRCRkQ.js:47649:18)
      at async loadAndTransform (file:///home/devp-sriram/gsap/3d/node_modules/vite/dist/node/chunks/dep-B0fRCRkQ.js:41320:27)
10:20:39 PM [vite] (client) Pre-transform error: Cannot apply unknown utility class: flex-center
  Plugin: @tailwindcss/vite:generate:serve
  File: /home/devp-sriram/gsap/3d/src/index.css

```

this is my css

```css

@import "tailwindcss";

@tailwind base;
@tailwind components;
@tailwind utilities;

@theme{
  --color-blue : #2997FF;
  --color-zinc : #101010;
  --color-gray-DEFAULT : #000;
  --color-gray : #033;
  --color-gray-100 : #94928d;
}


* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  color: white;
  width: 100dvw;
  overflow-x: hidden;
  height: 100%;
  background: #000;
  border-color: #3b3b3b;
  user-select: none;
}

canvas {
  touch-action: none;
}

.scrim-max-width {
  margin-inline-start: auto;
  margin-inline-end: auto;
  position: relative;
  max-width: 1120px;
}

@layer utilities {
  .flex-center {
    @apply flex items-center justify-center
  }

  .nav-height {
    @apply h-[calc(100vh-60px)]
  }
}
```
